### ISSUE TITLE
tooltip "info" icon doesn't render properly on some phone(s)

### ISSUE THREAD

**Issue by dan-da** [Neptune-Crypto/neptune-explorer#6]
received a report:

> on my phone, the tooltip icon is not rendered correctly. Probably on my end, but it's a pretty vanilla end at that, ie, I have no custom configuration on my phone.

note: The tooltip icon is presently this utf-8 char:  🛈

**Comment by dan-da** [comment]
This sounds like the mobile device's font does not have a glyph for 🛈.

unicode char 9432 ⓘ is also an i in a circle.  If it reliably display on the mobile device (and most all devices), it could be an acceptable substitute.   It displays better bolded.    **ⓘ**

**Comment by dan-da** [comment]
switched to ⓘ in dd7e80298db4ccd1607fdfdd956048e5170fc684.

already deployed.

not yet confirmed if this is an improvement or not.  leaving open.

**Comment by jan-ferdinand** [comment]
Yep, that works. :blush::+1:
